name: Pip Installer
author: BSFishy
description: An action to automatically install Pip packages
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'arrow-down'
  color: 'green'
inputs:
  packages:
    description: 'The packages to install from Pip'
    required: true
